### ISSUE TITLE
muted option not working

### ISSUE THREAD

**Issue by beiro** [jaagr/lemonbuddy#96]
I update today to the latest version, and muted option in volume module isnt working anymore.

**Comment by jaagr** [comment]
It works fine for me. Could you show me your config?

**Comment by jaagr** [comment]
And the output of
~~~sh
$ amixer scontrols
~~~

**Comment by beiro** [comment]
the volume part, as almost the whole config i took from your latest config:

[module/volume]
type = internal/volume
speaker-mixer = Speaker
headphone-mixer = Headphone
headphone-id = 9

format-volume = <ramp-volume> <label-volume>

label-volume = %percentage%
label-volume-foreground = #ccc

label-muted = %{F#66}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-foreground = #477ab3

ramp-headphones-0 = 
ramp-headphones-1 = 

amixer scontrols output:
Simple mixer control 'Master',0
Simple mixer control 'Capture',0

**Comment by jaagr** [comment]
wops, I edited your comment by mistake.. dunno how to revert

**Comment by beiro** [comment]
deleting the above, i still get the following error:
error: volume_module: Failed to open 'Speaker' mixer => Cannot find simple element

In the previous version this was my config:
<pre>
<code>[module/volume]
type = internal/volume
format-volume =   <label-volume>
label-muted =  muted</code>
</pre>
Was working fine, but with the update this doesnt work either.

**Comment by jaagr** [comment]
I think I found the change that caused it to stop working for you. I will commit a patch, hold on.

**Comment by jaagr** [comment]
Ok it should be fixed. Make sure you do not specify `speaker-mixer` or `headphone-mixer` since they were used to my setup and wouldn't work for you.

**Comment by beiro** [comment]
Not totally fixed.Let me try to explain.
So now i click the volume area and the sound gets muted, but doesnt change to the muted icon.If i click again does nothing, but if i change the volume the muted icon appears and the sound is still off.I click the icon again and the soud returns but the icon is still muted until i change the volume again with my keyboard combo keys. A bit strange to explain, but at least i can mute the sound now.

**Comment by jaagr** [comment]
To be honest I don't understand a thing. Could you make a gif or record your desktop?

**Comment by jaagr** [comment]
What command do you call when using your keyboard combo?

**Comment by beiro** [comment]
ctrl + {Down,Up}
    amixer sset Master 5%{-,+}

**Comment by beiro** [comment]
ctrl + {Down,Up}
    amixer sset Master 5%{-,+}

**Comment by beiro** [comment]
https://drive.google.com/open?id=0B6JBARL3tohRVTBKbE5KZmZUWU0

to the video: first touch mutes, change volume and icons turns to the muted icon, and only after this i can toggle on again, change volume again to percentage appears

**Comment by jaagr** [comment]
Could you try removing all other modules to make sure it's not caused by something else. That's an awesome wallpaper by the way, do you have a link to it?

**Comment by beiro** [comment]
wallpaper link: https://drive.google.com/open?id=0B6JBARL3tohRZElVVDIzbmNONEU

Removed all other modules, but this little issue persists.

**Comment by jaagr** [comment]
I can reproduce the issue... the same thing happens to me when I remove the mixer settings. Now I can look into it.

**Comment by jaagr** [comment]
Should be fixed with 21d91b0d91b007f8371791dc63642fbb5b8012bc, could you verify?

**Comment by beiro** [comment]
sorry , the latest behaviour persists,still have to change volumes between toggle on off. Im installing lemonbuddy-git, so that should get me the latest version right?

**Comment by jaagr** [comment]
I'll update the pkgrel for the aur package just to make sure.

**Comment by jaagr** [comment]
It's been updated.

**Comment by beiro** [comment]
The issue persists.
<pre>
<code>[module/volume]
type = internal/volume
format-volume = <ramp-volume> <label-volume>

label-volume = %percentage%
label-volume-foreground = #ccc

label-muted = %{F#66}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-foreground = #6495b6

ramp-headphones-0 = 
ramp-headphones-1 = </code>
</pre>

**Comment by jaagr** [comment]
I just pushed a commit that should fix it for reals. By the way, you can remove `ramp-headphones-N` since it will never be used without a defined headphone mixer.

**Comment by jaagr** [comment]
Please tell me if it solves your issue after testing.

**Comment by beiro** [comment]
Sorry for the delay.After build and install from source its working as intended. Thanks for your time.Keep up the good work:)

**Comment by jaagr** [comment]
Great :-)
